upstream odoo {
    server web:8069 max_fails=3 fail_timeout=10s;
    server web2:8069 max_fails=3 fail_timeout=10s;
}
upstream odoochat {
    server web:8072 max_fails=3 fail_timeout=10s;
    server web2:8072 max_fails=3 fail_timeout=10s;
}

server {
    listen 80;
    server_name odoo.wint.io.vn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name odoo.wint.io.vn;

    ssl_certificate /etc/letsencrypt/live/odoo.wint.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/odoo.wint.io.vn/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 100M;
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    # Hỗ trợ Websocket cho khung Chat / Discuss
    location /websocket {
        proxy_pass http://odoochat;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
        proxy_next_upstream_timeout 10s;
    }

    # Chan truy cap trang quan ly database tu ben ngoai internet
    location ~* /web/database {
        return 404;
    }

    # Chuyen tiep favicon.ico mac dinh ve duong dan favicon web cua Odoo
    location = /favicon.ico {
        proxy_pass http://odoo/web/static/img/favicon.ico;
    }

    # Thao tác web chính
    location / {
        proxy_pass http://odoo;
        proxy_redirect off;
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
        proxy_next_upstream_timeout 10s;

        sub_filter '/web/static/img/favicon.ico' '/favicon.ico?v=2';
        sub_filter_once off;
        sub_filter_types text/html;
    }

    # Tăng tốc cache file tĩnh CSS/JS
    location ~* /web/static/ {
        proxy_cache_valid 200 60m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo;
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
        proxy_next_upstream_timeout 10s;
    }

    gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
    gzip on;
}
